# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Kreutz - blog
email: tjkreutz@gmail.com
baseurl: ""
keep_files: []
destination: ../www
url: "http://www.timkreutz.nl" # the base hostname & protocol for your site
twitter_username: tjkreutz
github_username:  tjkreutz

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty

# Collections
collections:
  blog:
    output: true
  plog:
    output: true
  publications:
    output: true